artifact_location: file:///D:\OneDrive\Desktop\ml-ops_task7\mlflow_logs\mlflow_logs/696527973086188632
creation_time: 1733062066014
experiment_id: '696527973086188632'
last_update_time: 1733062066014
lifecycle_stage: active
name: Weather Forecast Experiment
