apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001  # This is a node port for external access
  type: NodePort
