apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30003  # This is a node port for external access
  type: NodePort
