artifact_location: file:///D:\OneDrive\Desktop\ml-ops_task7\mlflow_logs\mlflow_logs/0
creation_time: 1733062065977
experiment_id: '0'
last_update_time: 1733062065977
lifecycle_stage: active
name: Default
