name: CI Pipeline - Dev to Testing

on:
  push:
    branches:
      - testing

jobs:
  test-backend:
    name: Test Backend and Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python for Flask
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Backend Dependencies for Flask
        run: |
          cd Fullstack/Backend/Flask
          pip install -r requirements.txt

      - name: Run Backend Unit Tests for Flask
        run: |
          cd Fullstack/Backend/Flask
          pytest tests/

      - name: Set up Node.js for Express
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies for Express
        run: |
          cd Fullstack/Backend/Express
          npm install

      - name: Run Backend Unit Tests for Express
        run: |
          cd Fullstack/Backend
          pytest /tests

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Backend (Flask)
        run: |
          cd Fullstack/Backend/Flask
          docker build -t iboe0512/weather-app-backend-flask:latest .
          docker tag iboe0512/weather-app-backend-flask:latest iboe0512/weather-app-backend-flask:${{ github.sha }}
          docker push iboe0512/weather-app-backend-flask:latest
          docker push iboe0512/weather-app-backend-flask:${{ github.sha }}

      - name: Build and Push Docker Image for Backend (Express)
        run: |
          cd Fullstack/Backend/Express
          docker build -t  iboe0512/weather-app-backend-express:latest .
          docker tag iboe0512/weather-app-backend-express:latest iboe0512/weather-app-backend-express:${{ github.sha }}
          docker push iboe0512/weather-app-backend-express:latest
          docker push iboe0512/weather-app-backend-express:${{ github.sha }}

  test-frontend:
    name: Test Frontend and Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: |
          cd Fullstack/Frontend
          npm install

      - name: Run Frontend Unit Tests
        run: |
          cd Fullstack/Frontend
          npm test -- --watchAll=false --coverage

      - name: Build and Push Docker Image for Frontend
        run: |
          cd Fullstack/Frontend
          docker build -t iboe0512/weather-app-frontend:latest .
          docker tag iboe0512/weather-app-frontend:latest iboe0512/weather-app-frontend:${{ github.sha }}
          docker push iboe0512/weather-app-frontend:latest
          docker push iboe0512/weather-app-frontend:${{ github.sha }}
