name: CD Pipeline - Testing to Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Minikube
      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      # Deploy Docker Image to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl create deployment weather-app --image=iboe0512/weather-app:latest
          kubectl expose deployment weather-app --type=LoadBalancer --port=5000
          kubectl get services weather-app
